name: Bug report
description: Report a problem or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this form to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The page should load without errors
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: The page showed an error message - "..."
    validations:
      required: true

  - type: input
    id: screenshots
    attributes:
      label: Screenshots / Recordings
      description: If applicable, add screenshots or a recording to help explain your problem
      placeholder: https://example.com/screenshot.png

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running Glanced Reader?
      options:
        - Docker (recommended)
        - Docker Compose
        - Manual setup
        - Development (make dev)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser (if applicable)
      description: Which browser are you using?
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Other
      default: 0

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Paste any relevant logs or error messages
      render: shell
      placeholder: Error - Something went wrong

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      options:
        - label: I've searched for similar issues
          required: true
        - label: I'm using the latest version
          required: true
